[package]
name = "almon"
version = "0.1.0"
authors = ["Max Erdelmeier"]
edition = "2021"

[dependencies]
glium = "0.32.1"
cgmath = "0.18.0"
image = "0.24.4"
hecs = "0.9.0"
ahash = "0.8.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
